server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: vviyht7846.
      url: jdbc:mysql://47.113.144.50:3306/shortvideo?serverTimezone=GMT%2B8

qiniu:
  domainOfBucket : http://s3c51zvtx.hn-bkt.clouddn.com
  accessKey : w3VdBuR5aZoHP-v3NIjNJiOh0DwEq5Fh9EtQj1rM
  secretKey : Aog2_0SGoZ0IXNltTpn9pPcxsl0R7oPkNW_AMQGO

